export const SERVICES = [
  {
    slug: "diabetes",
    title: "Diabetes y Tecnología Aplicada",
    tagline: "Diagnóstico, control y seguimiento con tecnología de vanguardia en Barinas",
    icon: "diabetes",
    image: "/images/OZR_7472 (1).jpg",
    seo: {
      title: "Tratamiento de Diabetes en Barinas | Endocrinóloga | Dra. Jennifer Manrique",
      description:
        "Diagnóstico y tratamiento de diabetes tipo 1, tipo 2 y gestacional en Barinas. Endocrinóloga certificada con monitores continuos de glucosa. Consulta con la mejor endocrinóloga en Venezuela.",
      keywords: [
        "diabetes Barinas",
        "endocrinóloga diabetes Barinas",
        "tratamiento diabetes Barinas",
        "monitor continuo glucosa Barinas",
        "endocrino diabetes Venezuela",
        "endocrinólogo diabetes Venezuela",
        "diabetes tipo 2 Barinas",
        "control diabetes Venezuela",
        "insulina Barinas",
        "Dra Jennifer Manrique diabetes",
        "endocrinólogo Venezuela diabetes",
      ],
    },
    description: [
      "La Dra. Jennifer Manrique ofrece en Barinas una atención integral para pacientes con diabetes tipo 1, tipo 2 y gestacional, combinando el manejo clinico con el uso de tecnologías de vanguardia en el control glucémico.",
      "Cómo endocrinóloga en Barinas con formación especializada en tecnología aplicada a la diabetes, evalua cada caso de forma individual considerando el estilo de vida, los antecedentes familiares y las metas terapeuticas del paciente para diseñar un plan personalizado.",
      "En Venezuela, contar con una endocrinóloga en Barinas formada en los centros de referencia más importantes del pais y con entrenamiento internacional marca una diferencia significativa en la calidad del control metabólico.",
    ],
    conditions: [
      "Diabetes tipo 1",
      "Diabetes tipo 2",
      "Diabetes gestacional",
      "Prediabetes y resistencia a la insulina",
      "Hiperglicemia de estres",
      "Control glucémico durante el embarazo",
    ],
    treatments: [
      "Evaluación y ajuste de insulina",
      "Terapia con análogos de GLP-1 (Ozempic, Mounjaro)",
      "Colocacion y lectura de monitores continuos de glucosa",
      "Optimizacion de tratamiento oral e inyectable",
      "Educación diabetologica personalizada",
      "Plan integral de alimentación y actividad fisica",
    ],
    faqs: [
      {
        q: "Dónde tratar la diabetes con un endocrinólogo en Barinas?",
        a: "La Dra. Jennifer Manrique atiende en el Hospital Privado San Juan, Consultorio 34, Piso 2, Barinas. Es la endocrinóloga de la region con mayor formación actualizada en diabetes y tecnología de monitoreo continuo de glucosa.",
      },
      {
        q: "Qué diferencia hay entre un médico general y un endocrinólogo para tratar la diabetes?",
        a: "El endocrinólogo tiene formación especifica en el ajuste de insulinas, uso de tecnologías avanzadas, manejo de complicaciónes y protocolos actualizados. En Venezuela, ver a un endocrinólogo para la diabetes mejora significativamente el control a largo plazo.",
      },
      {
        q: "Usan tecnología de monitoreo continuo de glucosa en Barinas?",
        a: "Si. La Dra. Manrique tiene formación en uso e interpretacion de monitores continuos de glucosa (CGM), una herramienta qué permite un control mucho más preciso qué la glucometria tradicional.",
      },
    ],
  },
  {
    slug: "obesidad",
    title: "Manejo de Obesidad y Metabolismo",
    tagline: "Tratamiento médico de la obesidad con los avances más recientes en Venezuela",
    icon: "weight",
    image: "/images/OZR_7446 (1) (1).jpg",
    seo: {
      title: "Tratamiento Obesidad Barinas | Mounjaro Ozempic Venezuela | Dra. Jennifer Manrique",
      description:
        "Tratamiento médico de obesidad en Barinas con Mounjaro y Ozempic. GLP-1 disponibles en Venezuela con supervisión endocrinológica. Endocrinóloga certificada. Agenda tu consulta.",
      keywords: [
        "obesidad Barinas",
        "pérdida de peso Barinas",
        "Mounjaro Venezuela",
        "Mounjaro Barinas",
        "Ozempic Barinas",
        "Ozempic Venezuela",
        "GLP-1 Venezuela",
        "endocrinóloga obesidad Barinas",
        "tratamiento obesidad Venezuela",
        "endocrino obesidad Venezuela",
        "endocrinólogo obesidad Venezuela",
        "bajar de peso Barinas endocrino",
        "pérdida peso endocrinólogo Venezuela",
      ],
    },
    description: [
      "La obesidad es una enfermedad cronica compleja qué no se trata sólo con dieta y ejercicio. La Dra. Jennifer Manrique ofrece en Barinas un manejo médico integral evaluando las causas hormonales y metabólicas detras del sobrepeso.",
      "Cómo endocrinóloga en Barinas especializada en metabolismo, tiene experiencia en terapias modernas basadas en análogos de GLP-1 como Ozempic (semaglutida) y Mounjaro (tirzepatida), disponibles en Venezuela bajo indicación y supervisión médica.",
      "El tratamiento de la obesidad en Venezuela requiere un especialista qué entienda el componente hormonal. En Barinas, la Dra. Manrique es la referencia para el manejo médico del sobrepeso con enfoqué actualizado e integral.",
    ],
    conditions: [
      "Obesidad grado I, II y III",
      "Sobrepeso con factores de riesgo metabólico",
      "Resistencia a la insulina",
      "Síndrome metabólico",
      "Obesidad relaciónada a hipotiroidismo o SOP",
      "Obesidad en pacientes con diabetes tipo 2",
    ],
    treatments: [
      "Evaluación de causas hormonales del sobrepeso",
      "Terapia con Ozempic (semaglutida) GLP-1",
      "Terapia con Mounjaro (tirzepatida) GLP-1/GIP",
      "Plan de tratamiento fármacologico personalizado",
      "Control de colesterol, trigliceridos e insulina",
      "Seguimiento metabólico y ajuste de dosis",
    ],
    faqs: [
      {
        q: "Se consigue Mounjaro en Venezuela para perder peso?",
        a: "Si, actualmente Mounjaro (tirzepatida) se consigue en Venezuela. Su uso requiere evaluación médica previa e indicación de un endocrinologo. La Dra. Manrique puede evaluarte y orientarte sobre la opcion adecuada en Barinas.",
      },
      {
        q: "Cuándo debo ver un endocrinólogo y no sólo un nutriciónista para bajar de peso?",
        a: "Cuándo existen causas hormonales (hipotiroidismo, SOP, resistencia a insulina), cuándo la dieta y ejercicio no funciónan despues de meses de esfuerzo real, o cuándo el IMC supera 30 con comorbilidades cómo diabetes o hipertensión.",
      },
      {
        q: "La pérdida de peso con GLP-1 es permanente?",
        a: "Los médicamentos GLP-1 son herramientas dentro de un plan integral. El mantenimiento a largo plazo requiere cambios de hábitos. La Dra. Manrique diseña un plan completo qué incluye medicación, seguimiento clinico y educación.",
      },
    ],
  },
  {
    slug: "tiroides",
    title: "Patologias Tiroideas",
    tagline: "Evaluación y tratamiento completo de enfermedades de la tiroides en Barinas",
    icon: "thyroid",
    image: "/images/dr-jennifer-hero.jpg",
    seo: {
      title: "Endocrinóloga Tiroides Barinas | Hipotiroidismo Venezuela | Dra. Jennifer Manrique",
      description:
        "Diagnóstico y tratamiento de hipotiroidismo, hipertiroidismo y nódulos tiroideos en Barinas. Ecografía tiroidea y PAAF disponibles. Endocrinóloga certificada en Venezuela.",
      keywords: [
        "tiroides Barinas",
        "hipotiroidismo Barinas",
        "hipertiroidismo Barinas",
        "nódulos tiroideos Barinas",
        "ecografía tiroidea Barinas",
        "PAAF tiroides Venezuela",
        "endocrinóloga tiroides Barinas",
        "endocrino tiroides Venezuela",
        "endocrinólogo tiroides Venezuela",
        "tratamiento tiroides Venezuela",
        "Hashimoto Venezuela Barinas",
      ],
    },
    description: [
      "La tiroides es una glándula pequeña con una influencia enorme sobre el organismo. La Dra. Jennifer Manrique es endocrinóloga en Barinas con formación especializada en el diagnóstico y tratamiento de todas las patologias tiroideas.",
      "En Venezuela, las enfermedades de la tiroides son altamente prevalentes y frecuentemente subdiagnosticadas. En Barinas, contar con una endocrinóloga qué ofrece evaluación clínica, ecografía y biopsia por punción (PAAF) representa una ventaja significativa para los pacientes.",
      "Tanto el hipotiroidismo cómo el hipertiroidismo pueden afectar el peso, el estado de animo, la fertilidad, la presión arterial y la calidad de vida en general. Un diagnóstico preciso y un tratamiento ajustado marcan una diferencia real en el bienestar del paciente.",
    ],
    conditions: [
      "Hipotiroidismo primario y central",
      "Hipertiroidismo y enfermedad de Graves",
      "Nódulos tiroideos benignos y malignos",
      "Tiroiditis de Hashimoto",
      "Bocio simple y multinodular",
      "Cancer tiroideo diferenciado",
    ],
    treatments: [
      "Evaluación clínica y perfil tiroideo completo",
      "Ecografía tiroidea de alta resolución",
      "Punción con aguja fina (PAAF) de nódulos",
      "Tratamiento con levotiroxina ajustado",
      "Seguimiento post-cirugía tiroidea",
      "Manejo de tiroiditis autoinmune (Hashimoto)",
    ],
    faqs: [
      {
        q: "Qué síntomás indican qué debo ver un endocrinólogo para la tiroides en Barinas?",
        a: "Cansancio sin causa aparente, cambios de peso, caída de cabello, intolerancia al frio o calor, cambios en el ritmo cardiaco o alteraciones menstruales pueden estar relaciónados con la tiroides. Una consulta con endocrinóloga en Barinas permite el diagnóstico adecuado.",
      },
      {
        q: "Hacen ecografía y PAAF de tiroides en Barinas?",
        a: "Si. La Dra. Manrique coordina la evaluación completa en Barinas, incluyendo ecografía y punción de nódulos (PAAF) cuándo esta indicada, para obtener un diagnóstico preciso.",
      },
      {
        q: "El hipotiroidismo se cura o es de por vida?",
        a: "En la mayoria de los casos requiere tratamiento de por vida con levotiroxina. Con la dosis correcta y seguimiento regular, los pacientes llevan una vida completamente normal.",
      },
    ],
  },
  {
    slug: "salud-hormonal",
    title: "Salud Hormonal",
    tagline: "Diagnóstico y tratamiento de trastornos hormonales en hombres y mujeres en Barinas",
    icon: "hormone",
    image: "/images/OZR_7464 (1).jpg",
    seo: {
      title: "Endocrinóloga Salud Hormonal Barinas | SOP Venezuela | Dra. Jennifer Manrique",
      description:
        "Tratamiento de SOP, menopausia, andropausia y trastornos hormonales en Barinas. Endocrinóloga especializada en salud hormonal en Venezuela. Consulta previa cita.",
      keywords: [
        "SOP Barinas",
        "ovario poliquístico Barinas",
        "menopausia Barinas",
        "andropausia Venezuela",
        "salud hormonal Barinas",
        "endocrinóloga hormonas Barinas",
        "endocrino hormonal Venezuela",
        "endocrinólogo SOP Venezuela",
        "tratamiento hormonal Venezuela",
        "hipófisis endocrinólogo Venezuela",
        "suprarrenales endocrinólogo Barinas",
      ],
    },
    description: [
      "El sistema endocrino regula el metabolismo, el estado de animo, la fertilidad, el peso, el sueno y la energia. La Dra. Jennifer Manrique es endocrinóloga en Barinas especializada en el diagnóstico y tratamiento de trastornos hormonales en hombres y mujeres.",
      "El SOP, la menopausia, la andropausia, los tumores de hipófisis y las enfermedades suprarrenales requieren la atención de un especialista. En Venezuela, acceder a una endocrinóloga en Barinas con formación actualizada es clave para recibir tratamiento adecuado y oportuno.",
      "Con un enfoqué personalizado, la Dra. Manrique evalua el perfil hormonal completo de cada paciente para identificar desequilibrios y diseñar un plan de tratamiento qué mejore la calidad de vida de forma efectiva y segura.",
    ],
    conditions: [
      "Síndrome de ovario poliquístico (SOP)",
      "Menopausia y perimenopausia",
      "Andropausia y deficiencia de testosterona",
      "Alteraciones de la hipófisis (prolactinoma)",
      "Enfermedades suprarrenales (Cushing, Addison)",
      "Trastornos del cortisol",
    ],
    treatments: [
      "Perfil hormonal completo (FSH, LH, estradiol, testosterona, cortisol)",
      "Tratamiento fármacologico del SOP",
      "Terapia hormonal en menopausia y andropausia",
      "Manejo de prolactinoma con cabergolina",
      "Seguimiento de tumores hipofisarios",
      "Evaluación y tratamiento de suprarrenales",
    ],
    faqs: [
      {
        q: "Cómo saber si tengo SOP y dónde consultarlo en Barinas?",
        a: "El SOP se diagnostica con evaluación clínica, perfil hormonal y ecografía. Sintomás frecuentes: ciclos irregulares, acne, vello excesivo, dificultad para bajar de peso. La Dra. Manrique atiende SOP en Barinas con abordaje hormonal y metabólico.",
      },
      {
        q: "La menopausia se puede tratar con un endocrinólogo en Venezuela?",
        a: "Si. El endocrinólogo evalua el impacto metabólico y hormonal: cambios de peso, resistencia a la insulina, pérdida osea y síntomás vasomotores. La Dra. Manrique ofrece orientación y tratamiento en Barinas.",
      },
      {
        q: "Los hombres también necesitan un endocrinólogo para problemas hormonales?",
        a: "Si. La andropausia, la deficiencia de testosterona y los tumores de hipófisis requieren evaluación endocrinológica. La Dra. Manrique atiende trastornos hormonales en hombres y mujeres en Barinas.",
      },
    ],
  },
  {
    slug: "fertilidad",
    title: "Fertilidad y Salud Reproductiva",
    tagline: "Evaluación hormonal y acompañamiento para la fertilidad en Barinas",
    icon: "fertility",
    image: "/images/OZR_7617 (1).jpg",
    seo: {
      title: "Endocrinóloga Fertilidad Barinas | Evaluación Hormonal Venezuela | Dra. Jennifer Manrique",
      description:
        "Evaluación hormonal para fertilidad, hipogonadismo y protocolos pre-concepcionales en Barinas. Endocrinóloga especializada en salud reproductiva en Venezuela. Agenda tu consulta.",
      keywords: [
        "fertilidad hormonal Barinas",
        "endocrinóloga fertilidad Barinas",
        "evaluación hormonal fertilidad Venezuela",
        "hipogonadismo Venezuela",
        "endocrino fertilidad Venezuela",
        "endocrinólogo fertilidad Venezuela",
        "infertilidad hormonal Barinas",
        "protocolo preconcepcional Venezuela",
        "embarazo hormonal Barinas",
        "optimización hormonal embarazo Venezuela",
      ],
    },
    description: [
      "Los trastornos hormonales son una de las causas más frecuentes de infertilidad tanto en mujeres cómo en hombres. La Dra. Jennifer Manrique, endocrinóloga en Barinas, ofrece evaluación hormonal completa y tratamiento orientado a optimizar las condiciónes para lograr un embarazo.",
      "El componente endocrino de la fertilidad incluye la tiroides, el eje hipotalamo-hipófisis-gonadas, la prolactina, la insulina y las hormonas sexuales. Un desequilibrio en cualquiera de estos sistemas puede dificultar o impedir la concepcion.",
      "En Venezuela, la coordinación entre el endocrinólogo y el ginecologo es clave para abordar la infertilidad de origen hormonal. En Barinas, la Dra. Manrique es la especialista de referencia para este tipo de evaluación.",
    ],
    conditions: [
      "Infertilidad de causa hormonal",
      "Hipogonadismo masculino y femeniño",
      "Hiperprolactinemia",
      "Disfunción tiroidea y fertilidad",
      "SOP e infertilidad",
      "Deficiencia de LH o FSH",
    ],
    treatments: [
      "Evaluación hormonal completa (FSH, LH, prolactina, AMH)",
      "Protocolo pre-concepcional personalizado",
      "Tratamiento de hipotiroidismo en el embarazo",
      "Manejo hormonal del hipogonadismo",
      "Optimizacion de testosterona e insulina",
      "Coordinación con ginecologia según el caso",
    ],
    faqs: [
      {
        q: "Cuándo debo ver a un endocrinólogo por problemas de fertilidad en Barinas?",
        a: "Si llevas más de un ano intentando embarazarte, tienes ciclos irregulares, hipotiroidismo, SOP, prolactina elevada o antecedentes de abortos repetidos. La evaluación endocrinológica en Barinas identifica causas hormonales tratables.",
      },
      {
        q: "El hipotiroidismo afecta la fertilidad en Venezuela?",
        a: "Si. El hipotiroidismo no tratado puede dificultar la ovulacion y aumentar el riesgo de aborto. La Dra. Manrique optimiza el control tiroideo antes y durante el embarazo en Barinas.",
      },
      {
        q: "Los hombres con problemas de fertilidad deben ver a un endocrinologo?",
        a: "Si. La deficiencia de testosterona, el hipogonadismo y la hiperprolactinemia son causas endocrinas de infertilidad masculina. La evaluación en Barinas permite identificar y tratar estas condiciónes.",
      },
    ],
  },
  {
    slug: "crecimiento",
    title: "Crecimiento y Desarrollo",
    tagline: "Evaluación y tratamiento de alteraciones del crecimiento en niños y adolescentes",
    icon: "growth",
    image: "/images/dr-jennifer-about.jpg",
    seo: {
      title: "Endocrinóloga Talla Baja Barinas | Crecimiento Venezuela | Dra. Jennifer Manrique",
      description:
        "Evaluación de talla baja, pubertad precoz y deficiencia de hormona de crecimiento en Barinas. Endocrinóloga en Venezuela especializada en crecimiento y desarrollo. Atención previa cita.",
      keywords: [
        "talla baja Barinas",
        "endocrinóloga crecimiento Barinas",
        "pubertad precoz Venezuela",
        "hormona de crecimiento Venezuela",
        "endocrino niños Venezuela",
        "endocrinólogo pediatrico Venezuela",
        "crecimiento niños Barinas",
        "desarrollo pubertad Barinas",
        "endocrinólogo talla baja Venezuela",
        "pubertad retrasada Venezuela",
      ],
    },
    description: [
      "El crecimiento y el desarrollo puberal son procesos regulados por el sistema endocrino. La Dra. Jennifer Manrique, endocrinóloga en Barinas, evalua y trata las alteraciones del crecimiento en niños y adolescentes.",
      "En Venezuela, la deteccion temprana de una deficiencia de hormona de crecimiento o una alteracion puberal puede marcar la diferencia en la talla final y en el desarrollo integral del niño. Barinas cuenta con una endocrinóloga formada en estos protocolos especializados.",
      "La evaluación del crecimiento requiere análisis clinico, estudios hormonales especificos y en ocasiones pruebas de estimulacion. La Dra. Manrique diseña un plan de seguimiento personalizado para cada caso.",
    ],
    conditions: [
      "Talla baja de causa endocrina",
      "Deficiencia de hormona de crecimiento",
      "Pubertad precoz (antes de los 8 en ninas y 9 en niños)",
      "Pubertad retrasada",
      "Hipotiroidismo en niños",
      "Talla baja idiopatica con evaluación hormonal",
    ],
    treatments: [
      "Evaluación clínica de la curva de crecimiento",
      "Perfil hormonal (GH, IGF-1, TSH, FSH, LH)",
      "Prueba de estimulacion de hormona de crecimiento",
      "Tratamiento con hormona de crecimiento recombinante",
      "Manejo de pubertad precoz con análogos GnRH",
      "Seguimiento longitudinal del desarrollo puberal",
    ],
    faqs: [
      {
        q: "Cuándo debo consultar a una endocrinóloga por la talla de mi hijo en Barinas?",
        a: "Si tu hijo crece menos de 5 cm por ano, esta por debajo del percentil 3 para su edad, o hay una diferencia significativa con la talla esperada según la de los padres. Una evaluación endocrinológica en Barinas es el primer paso.",
      },
      {
        q: "La pubertad precoz se puede tratar en Venezuela?",
        a: "Si. La pubertad precoz tiene tratamiento efectivo con análogos de GnRH. La Dra. Manrique puede orientarte y manejar el caso en Barinas con el protocolo adecuado.",
      },
      {
        q: "La hormona de crecimiento esta disponible en Venezuela?",
        a: "Si, existen presentaciones disponibles en Venezuela. Su uso requiere evaluación especializada, estudios hormonales confirmatorios y prescripción médica. La Dra. Manrique realiza la evaluación completa en Barinas.",
      },
    ],
  },
];
