export const SERVICES = [
  {
    slug: "diabetes",
    title: "Diabetes y Tecnologia Aplicada",
    tagline: "Diagnostico, control y seguimiento con tecnologia de vanguardia en Barinas",
    icon: "diabetes",
    image: "/images/OZR_7472 (1).jpg",
    seo: {
      title: "Tratamiento de Diabetes en Barinas | Endocrinologa | Dra. Jennifer Manrique",
      description:
        "Diagnostico y tratamiento de diabetes tipo 1, tipo 2 y gestacional en Barinas. Endocrinologa certificada con monitores continuos de glucosa. Consulta con la mejor endocrinologa en Venezuela.",
      keywords: [
        "diabetes Barinas",
        "endocrinologa diabetes Barinas",
        "tratamiento diabetes Barinas",
        "monitor continuo glucosa Barinas",
        "endocrino diabetes Venezuela",
        "endocrinologo diabetes Venezuela",
        "diabetes tipo 2 Barinas",
        "control diabetes Venezuela",
        "insulina Barinas",
        "Dra Jennifer Manrique diabetes",
        "endocrinologo Venezuela diabetes",
      ],
    },
    description: [
      "La Dra. Jennifer Manrique ofrece en Barinas una atencion integral para pacientes con diabetes tipo 1, tipo 2 y gestacional, combinando el manejo clinico con el uso de tecnologias de vanguardia en el control glucemico.",
      "Como endocrinologa en Barinas con formacion especializada en tecnologia aplicada a la diabetes, evalua cada caso de forma individual considerando el estilo de vida, los antecedentes familiares y las metas terapeuticas del paciente para disenar un plan personalizado.",
      "En Venezuela, contar con una endocrinologa en Barinas formada en los centros de referencia mas importantes del pais y con entrenamiento internacional marca una diferencia significativa en la calidad del control metabolico.",
    ],
    conditions: [
      "Diabetes tipo 1",
      "Diabetes tipo 2",
      "Diabetes gestacional",
      "Prediabetes y resistencia a la insulina",
      "Hiperglicemia de estres",
      "Control glucemico durante el embarazo",
    ],
    treatments: [
      "Evaluacion y ajuste de insulina",
      "Terapia con analogos de GLP-1 (Ozempic, Mounjaro)",
      "Colocacion y lectura de monitores continuos de glucosa",
      "Optimizacion de tratamiento oral e inyectable",
      "Educacion diabetologica personalizada",
      "Plan integral de alimentacion y actividad fisica",
    ],
    faqs: [
      {
        q: "Donde tratar la diabetes con un endocrinologo en Barinas?",
        a: "La Dra. Jennifer Manrique atiende en el Hospital Privado San Juan, Consultorio 34, Piso 2, Barinas. Es la endocrinologa de la region con mayor formacion actualizada en diabetes y tecnologia de monitoreo continuo de glucosa.",
      },
      {
        q: "Que diferencia hay entre un medico general y un endocrinologo para tratar la diabetes?",
        a: "El endocrinologo tiene formacion especifica en el ajuste de insulinas, uso de tecnologias avanzadas, manejo de complicaciones y protocolos actualizados. En Venezuela, ver a un endocrinologo para la diabetes mejora significativamente el control a largo plazo.",
      },
      {
        q: "Usan tecnologia de monitoreo continuo de glucosa en Barinas?",
        a: "Si. La Dra. Manrique tiene formacion en uso e interpretacion de monitores continuos de glucosa (CGM), una herramienta que permite un control mucho mas preciso que la glucometria tradicional.",
      },
    ],
  },
  {
    slug: "obesidad",
    title: "Manejo de Obesidad y Metabolismo",
    tagline: "Tratamiento medico de la obesidad con los avances mas recientes en Venezuela",
    icon: "weight",
    image: "/images/OZR_7446 (1) (1).jpg",
    seo: {
      title: "Tratamiento Obesidad Barinas | Mounjaro Ozempic Venezuela | Dra. Jennifer Manrique",
      description:
        "Tratamiento medico de obesidad en Barinas con Mounjaro y Ozempic. GLP-1 disponibles en Venezuela con supervision endocrinologica. Endocrinologa certificada. Agenda tu consulta.",
      keywords: [
        "obesidad Barinas",
        "perdida de peso Barinas",
        "Mounjaro Venezuela",
        "Mounjaro Barinas",
        "Ozempic Barinas",
        "Ozempic Venezuela",
        "GLP-1 Venezuela",
        "endocrinologa obesidad Barinas",
        "tratamiento obesidad Venezuela",
        "endocrino obesidad Venezuela",
        "endocrinologo obesidad Venezuela",
        "bajar de peso Barinas endocrino",
        "perdida peso endocrinologo Venezuela",
      ],
    },
    description: [
      "La obesidad es una enfermedad cronica compleja que no se trata solo con dieta y ejercicio. La Dra. Jennifer Manrique ofrece en Barinas un manejo medico integral evaluando las causas hormonales y metabolicas detras del sobrepeso.",
      "Como endocrinologa en Barinas especializada en metabolismo, tiene experiencia en terapias modernas basadas en analogos de GLP-1 como Ozempic (semaglutida) y Mounjaro (tirzepatida), disponibles en Venezuela bajo indicacion y supervision medica.",
      "El tratamiento de la obesidad en Venezuela requiere un especialista que entienda el componente hormonal. En Barinas, la Dra. Manrique es la referencia para el manejo medico del sobrepeso con enfoque actualizado e integral.",
    ],
    conditions: [
      "Obesidad grado I, II y III",
      "Sobrepeso con factores de riesgo metabolico",
      "Resistencia a la insulina",
      "Sindrome metabolico",
      "Obesidad relacionada a hipotiroidismo o SOP",
      "Obesidad en pacientes con diabetes tipo 2",
    ],
    treatments: [
      "Evaluacion de causas hormonales del sobrepeso",
      "Terapia con Ozempic (semaglutida) GLP-1",
      "Terapia con Mounjaro (tirzepatida) GLP-1/GIP",
      "Plan de tratamiento farmacologico personalizado",
      "Control de colesterol, trigliceridos e insulina",
      "Seguimiento metabolico y ajuste de dosis",
    ],
    faqs: [
      {
        q: "Se consigue Mounjaro en Venezuela para perder peso?",
        a: "Si, actualmente Mounjaro (tirzepatida) se consigue en Venezuela. Su uso requiere evaluacion medica previa e indicacion de un endocrinologo. La Dra. Manrique puede evaluarte y orientarte sobre la opcion adecuada en Barinas.",
      },
      {
        q: "Cuando debo ver un endocrinologo y no solo un nutricionista para bajar de peso?",
        a: "Cuando existen causas hormonales (hipotiroidismo, SOP, resistencia a insulina), cuando la dieta y ejercicio no funcionan despues de meses de esfuerzo real, o cuando el IMC supera 30 con comorbilidades como diabetes o hipertension.",
      },
      {
        q: "La perdida de peso con GLP-1 es permanente?",
        a: "Los medicamentos GLP-1 son herramientas dentro de un plan integral. El mantenimiento a largo plazo requiere cambios de habitos. La Dra. Manrique diseña un plan completo que incluye medicacion, seguimiento clinico y educacion.",
      },
    ],
  },
  {
    slug: "tiroides",
    title: "Patologias Tiroideas",
    tagline: "Evaluacion y tratamiento completo de enfermedades de la tiroides en Barinas",
    icon: "thyroid",
    image: "/images/dr-jennifer-hero.jpg",
    seo: {
      title: "Endocrinologa Tiroides Barinas | Hipotiroidismo Venezuela | Dra. Jennifer Manrique",
      description:
        "Diagnostico y tratamiento de hipotiroidismo, hipertiroidismo y nodulos tiroideos en Barinas. Ecografia tiroidea y PAAF disponibles. Endocrinologa certificada en Venezuela.",
      keywords: [
        "tiroides Barinas",
        "hipotiroidismo Barinas",
        "hipertiroidismo Barinas",
        "nodulos tiroideos Barinas",
        "ecografia tiroidea Barinas",
        "PAAF tiroides Venezuela",
        "endocrinologa tiroides Barinas",
        "endocrino tiroides Venezuela",
        "endocrinologo tiroides Venezuela",
        "tratamiento tiroides Venezuela",
        "Hashimoto Venezuela Barinas",
      ],
    },
    description: [
      "La tiroides es una glandula pequeña con una influencia enorme sobre el organismo. La Dra. Jennifer Manrique es endocrinologa en Barinas con formacion especializada en el diagnostico y tratamiento de todas las patologias tiroideas.",
      "En Venezuela, las enfermedades de la tiroides son altamente prevalentes y frecuentemente subdiagnosticadas. En Barinas, contar con una endocrinologa que ofrece evaluacion clinica, ecografia y biopsia por puncion (PAAF) representa una ventaja significativa para los pacientes.",
      "Tanto el hipotiroidismo como el hipertiroidismo pueden afectar el peso, el estado de animo, la fertilidad, la presion arterial y la calidad de vida en general. Un diagnostico preciso y un tratamiento ajustado marcan una diferencia real en el bienestar del paciente.",
    ],
    conditions: [
      "Hipotiroidismo primario y central",
      "Hipertiroidismo y enfermedad de Graves",
      "Nodulos tiroideos benignos y malignos",
      "Tiroiditis de Hashimoto",
      "Bocio simple y multinodular",
      "Cancer tiroideo diferenciado",
    ],
    treatments: [
      "Evaluacion clinica y perfil tiroideo completo",
      "Ecografia tiroidea de alta resolucion",
      "Puncion con aguja fina (PAAF) de nodulos",
      "Tratamiento con levotiroxina ajustado",
      "Seguimiento post-cirugia tiroidea",
      "Manejo de tiroiditis autoinmune (Hashimoto)",
    ],
    faqs: [
      {
        q: "Que sintomas indican que debo ver un endocrinologo para la tiroides en Barinas?",
        a: "Cansancio sin causa aparente, cambios de peso, caida de cabello, intolerancia al frio o calor, cambios en el ritmo cardiaco o alteraciones menstruales pueden estar relacionados con la tiroides. Una consulta con endocrinologa en Barinas permite el diagnostico adecuado.",
      },
      {
        q: "Hacen ecografia y PAAF de tiroides en Barinas?",
        a: "Si. La Dra. Manrique coordina la evaluacion completa en Barinas, incluyendo ecografia y puncion de nodulos (PAAF) cuando esta indicada, para obtener un diagnostico preciso.",
      },
      {
        q: "El hipotiroidismo se cura o es de por vida?",
        a: "En la mayoria de los casos requiere tratamiento de por vida con levotiroxina. Con la dosis correcta y seguimiento regular, los pacientes llevan una vida completamente normal.",
      },
    ],
  },
  {
    slug: "salud-hormonal",
    title: "Salud Hormonal",
    tagline: "Diagnostico y tratamiento de trastornos hormonales en hombres y mujeres en Barinas",
    icon: "hormone",
    image: "/images/OZR_7464 (1).jpg",
    seo: {
      title: "Endocrinologa Salud Hormonal Barinas | SOP Venezuela | Dra. Jennifer Manrique",
      description:
        "Tratamiento de SOP, menopausia, andropausia y trastornos hormonales en Barinas. Endocrinologa especializada en salud hormonal en Venezuela. Consulta previa cita.",
      keywords: [
        "SOP Barinas",
        "ovario poliquistico Barinas",
        "menopausia Barinas",
        "andropausia Venezuela",
        "salud hormonal Barinas",
        "endocrinologa hormonas Barinas",
        "endocrino hormonal Venezuela",
        "endocrinologo SOP Venezuela",
        "tratamiento hormonal Venezuela",
        "hipofisis endocrinologo Venezuela",
        "suprarrenales endocrinologo Barinas",
      ],
    },
    description: [
      "El sistema endocrino regula el metabolismo, el estado de animo, la fertilidad, el peso, el sueno y la energia. La Dra. Jennifer Manrique es endocrinologa en Barinas especializada en el diagnostico y tratamiento de trastornos hormonales en hombres y mujeres.",
      "El SOP, la menopausia, la andropausia, los tumores de hipofisis y las enfermedades suprarrenales requieren la atencion de un especialista. En Venezuela, acceder a una endocrinologa en Barinas con formacion actualizada es clave para recibir tratamiento adecuado y oportuno.",
      "Con un enfoque personalizado, la Dra. Manrique evalua el perfil hormonal completo de cada paciente para identificar desequilibrios y disenar un plan de tratamiento que mejore la calidad de vida de forma efectiva y segura.",
    ],
    conditions: [
      "Sindrome de ovario poliquistico (SOP)",
      "Menopausia y perimenopausia",
      "Andropausia y deficiencia de testosterona",
      "Alteraciones de la hipofisis (prolactinoma)",
      "Enfermedades suprarrenales (Cushing, Addison)",
      "Trastornos del cortisol",
    ],
    treatments: [
      "Perfil hormonal completo (FSH, LH, estradiol, testosterona, cortisol)",
      "Tratamiento farmacologico del SOP",
      "Terapia hormonal en menopausia y andropausia",
      "Manejo de prolactinoma con cabergolina",
      "Seguimiento de tumores hipofisarios",
      "Evaluacion y tratamiento de suprarrenales",
    ],
    faqs: [
      {
        q: "Como saber si tengo SOP y donde consultarlo en Barinas?",
        a: "El SOP se diagnostica con evaluacion clinica, perfil hormonal y ecografia. Sintomas frecuentes: ciclos irregulares, acne, vello excesivo, dificultad para bajar de peso. La Dra. Manrique atiende SOP en Barinas con abordaje hormonal y metabolico.",
      },
      {
        q: "La menopausia se puede tratar con un endocrinologo en Venezuela?",
        a: "Si. El endocrinologo evalua el impacto metabolico y hormonal: cambios de peso, resistencia a la insulina, perdida osea y sintomas vasomotores. La Dra. Manrique ofrece orientacion y tratamiento en Barinas.",
      },
      {
        q: "Los hombres tambien necesitan un endocrinologo para problemas hormonales?",
        a: "Si. La andropausia, la deficiencia de testosterona y los tumores de hipofisis requieren evaluacion endocrinologica. La Dra. Manrique atiende trastornos hormonales en hombres y mujeres en Barinas.",
      },
    ],
  },
  {
    slug: "fertilidad",
    title: "Fertilidad y Salud Reproductiva",
    tagline: "Evaluacion hormonal y acompanamiento para la fertilidad en Barinas",
    icon: "fertility",
    image: "/images/OZR_7617 (1).jpg",
    seo: {
      title: "Endocrinologa Fertilidad Barinas | Evaluacion Hormonal Venezuela | Dra. Jennifer Manrique",
      description:
        "Evaluacion hormonal para fertilidad, hipogonadismo y protocolos pre-concepcionales en Barinas. Endocrinologa especializada en salud reproductiva en Venezuela. Agenda tu consulta.",
      keywords: [
        "fertilidad hormonal Barinas",
        "endocrinologa fertilidad Barinas",
        "evaluacion hormonal fertilidad Venezuela",
        "hipogonadismo Venezuela",
        "endocrino fertilidad Venezuela",
        "endocrinologo fertilidad Venezuela",
        "infertilidad hormonal Barinas",
        "protocolo preconcepcional Venezuela",
        "embarazo hormonal Barinas",
        "optimizacion hormonal embarazo Venezuela",
      ],
    },
    description: [
      "Los trastornos hormonales son una de las causas mas frecuentes de infertilidad tanto en mujeres como en hombres. La Dra. Jennifer Manrique, endocrinologa en Barinas, ofrece evaluacion hormonal completa y tratamiento orientado a optimizar las condiciones para lograr un embarazo.",
      "El componente endocrino de la fertilidad incluye la tiroides, el eje hipotalamo-hipofisis-gonadas, la prolactina, la insulina y las hormonas sexuales. Un desequilibrio en cualquiera de estos sistemas puede dificultar o impedir la concepcion.",
      "En Venezuela, la coordinacion entre el endocrinologo y el ginecologo es clave para abordar la infertilidad de origen hormonal. En Barinas, la Dra. Manrique es la especialista de referencia para este tipo de evaluacion.",
    ],
    conditions: [
      "Infertilidad de causa hormonal",
      "Hipogonadismo masculino y femenino",
      "Hiperprolactinemia",
      "Disfuncion tiroidea y fertilidad",
      "SOP e infertilidad",
      "Deficiencia de LH o FSH",
    ],
    treatments: [
      "Evaluacion hormonal completa (FSH, LH, prolactina, AMH)",
      "Protocolo pre-concepcional personalizado",
      "Tratamiento de hipotiroidismo en el embarazo",
      "Manejo hormonal del hipogonadismo",
      "Optimizacion de testosterona e insulina",
      "Coordinacion con ginecologia segun el caso",
    ],
    faqs: [
      {
        q: "Cuando debo ver a un endocrinologo por problemas de fertilidad en Barinas?",
        a: "Si llevas mas de un ano intentando embarazarte, tienes ciclos irregulares, hipotiroidismo, SOP, prolactina elevada o antecedentes de abortos repetidos. La evaluacion endocrinologica en Barinas identifica causas hormonales tratables.",
      },
      {
        q: "El hipotiroidismo afecta la fertilidad en Venezuela?",
        a: "Si. El hipotiroidismo no tratado puede dificultar la ovulacion y aumentar el riesgo de aborto. La Dra. Manrique optimiza el control tiroideo antes y durante el embarazo en Barinas.",
      },
      {
        q: "Los hombres con problemas de fertilidad deben ver a un endocrinologo?",
        a: "Si. La deficiencia de testosterona, el hipogonadismo y la hiperprolactinemia son causas endocrinas de infertilidad masculina. La evaluacion en Barinas permite identificar y tratar estas condiciones.",
      },
    ],
  },
  {
    slug: "crecimiento",
    title: "Crecimiento y Desarrollo",
    tagline: "Evaluacion y tratamiento de alteraciones del crecimiento en ninos y adolescentes",
    icon: "growth",
    image: "/images/dr-jennifer-about.jpg",
    seo: {
      title: "Endocrinologa Talla Baja Barinas | Crecimiento Venezuela | Dra. Jennifer Manrique",
      description:
        "Evaluacion de talla baja, pubertad precoz y deficiencia de hormona de crecimiento en Barinas. Endocrinologa en Venezuela especializada en crecimiento y desarrollo. Atencion previa cita.",
      keywords: [
        "talla baja Barinas",
        "endocrinologa crecimiento Barinas",
        "pubertad precoz Venezuela",
        "hormona de crecimiento Venezuela",
        "endocrino ninos Venezuela",
        "endocrinologo pediatrico Venezuela",
        "crecimiento ninos Barinas",
        "desarrollo pubertad Barinas",
        "endocrinologo talla baja Venezuela",
        "pubertad retrasada Venezuela",
      ],
    },
    description: [
      "El crecimiento y el desarrollo puberal son procesos regulados por el sistema endocrino. La Dra. Jennifer Manrique, endocrinologa en Barinas, evalua y trata las alteraciones del crecimiento en ninos y adolescentes.",
      "En Venezuela, la deteccion temprana de una deficiencia de hormona de crecimiento o una alteracion puberal puede marcar la diferencia en la talla final y en el desarrollo integral del nino. Barinas cuenta con una endocrinologa formada en estos protocolos especializados.",
      "La evaluacion del crecimiento requiere analisis clinico, estudios hormonales especificos y en ocasiones pruebas de estimulacion. La Dra. Manrique diseña un plan de seguimiento personalizado para cada caso.",
    ],
    conditions: [
      "Talla baja de causa endocrina",
      "Deficiencia de hormona de crecimiento",
      "Pubertad precoz (antes de los 8 en ninas y 9 en ninos)",
      "Pubertad retrasada",
      "Hipotiroidismo en ninos",
      "Talla baja idiopatica con evaluacion hormonal",
    ],
    treatments: [
      "Evaluacion clinica de la curva de crecimiento",
      "Perfil hormonal (GH, IGF-1, TSH, FSH, LH)",
      "Prueba de estimulacion de hormona de crecimiento",
      "Tratamiento con hormona de crecimiento recombinante",
      "Manejo de pubertad precoz con analogos GnRH",
      "Seguimiento longitudinal del desarrollo puberal",
    ],
    faqs: [
      {
        q: "Cuando debo consultar a una endocrinologa por la talla de mi hijo en Barinas?",
        a: "Si tu hijo crece menos de 5 cm por ano, esta por debajo del percentil 3 para su edad, o hay una diferencia significativa con la talla esperada segun la de los padres. Una evaluacion endocrinologica en Barinas es el primer paso.",
      },
      {
        q: "La pubertad precoz se puede tratar en Venezuela?",
        a: "Si. La pubertad precoz tiene tratamiento efectivo con analogos de GnRH. La Dra. Manrique puede orientarte y manejar el caso en Barinas con el protocolo adecuado.",
      },
      {
        q: "La hormona de crecimiento esta disponible en Venezuela?",
        a: "Si, existen presentaciones disponibles en Venezuela. Su uso requiere evaluacion especializada, estudios hormonales confirmatorios y prescripcion medica. La Dra. Manrique realiza la evaluacion completa en Barinas.",
      },
    ],
  },
];
